### ISSUE TITLE
추가기능 제언드립니다.

### ISSUE THREAD

**Issue by ulgoon** [passersby-1/stopwatch#10]
이슈와 스크럼보드로 보았을 때 1차 마일스톤을 달성하신 것 같은데
끝나셨다면 main 브랜치로 release 및 추가기능 구현을 위한 이슈생성을 해보시면 좋을 것 같습니다.

**Comment by Jack2ee-dev** [comment]
네 스타일링을 위한 이슈 추가해보면 좋을 것 같습니다! 감사합니다~
