### ISSUE TITLE
Roles

### ISSUE THREAD

**Issue by Jack2ee-dev** [passersby-1/stopwatch#2]
1. 장지훈
- [x] index.html 마크업
- [ ] lap 기능 구현
- [ ] reset 기능 구현

2. 허재혁
- [ ] start 기능 구현
- [ ] stop 기능 구현
- [ ] resume 기능 구현

**Comment by passersby-1** [comment]
Index.html 구조 작성 완료 및 기본 세팅 완료

**Comment by Jack2ee-dev** [comment]
프로젝트는 레포 주인만 만들 수 있는 듯

**Comment by passersby-1** [comment]
만드는 중인데 힘드네용 흑

**Comment by Jack2ee-dev** [comment]
.eslintrc에서 parser로 babel-parser가 지정되었는데 package.json에 babel-parser가 없어서 에러가 납니다

**Comment by ulgoon** [comment]
> .eslintrc에서 parser로 babel-parser가 지정되었는데 package.json에 babel-parser가 없어서 에러가 납니다

이런 것을 이슈로 남기시면 좋아요^^ 라벨은 invalid 같은 걸 달아서^^
