### ISSUE TITLE
RESET 기능 구현

### ISSUE THREAD

**Issue by passersby-1** [passersby-1/stopwatch#8]
- [x] START가 안됬을시 RESET 버튼 비활성화
- [x] 타이머 작동 시 RESET 버튼 활성화
- [x] RESET 버튼 클릭시 타이머 초기화
- [x] RESET 버튼 클릭시 LAP 비활성화
- [x] RESET 버튼 클릭시 START 버튼 content를 START로 변경

**Comment by Jack2ee-dev** [comment]
reset은 너가 하기로 하지 않았어?

**Comment by passersby-1** [comment]
> reset은 너가 하기로 하지 않았어?

잘못 눌러서 다시 바꿈!
